import * as config from '../config'
import { generateRoot } from './generate-root'
import { generateScale } from './generate-scale'
import { generateTailwind } from './generate-tailwind'
import fs from 'fs'

const tailwind = generateTailwind(config)
const root = generateRoot(config)
const scale = generateScale()

const banner = `/*
 * THIS FILE IS GENERATED BY setup-styles.ts
 * DO NOT EDIT IT DIRECTLY.
 */`

const tailwindcss = [banner, tailwind, scale].join('\n\n')
const rootcss = [banner, root].join('\n\n')

if (typeof Bun !== 'undefined') {
  await Bun.write('./lib/styles/css/tailwind.css', tailwindcss)
  await Bun.write('./lib/styles/css/root.css', rootcss)
} else {
  fs.writeFileSync('./lib/styles/css/tailwind.css', tailwindcss)
  fs.writeFileSync('./lib/styles/css/root.css', rootcss)
}

console.log('✓ Style config generated successfully')

